import { drizzle } from "drizzle-orm/postgres-js";
import postgres from "postgres";
import { locations, locationPricing } from "./schema";
import { eq } from "drizzle-orm";

function slugify(name: string): string {
  return name
    .toLowerCase()
    .replace(/['']/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
}

const newLocations = [
  {
    name: "West Wycombe Park",
    slug: slugify("West Wycombe Park"),
    category: "house",
    region: "Buckinghamshire",
    latitude: "51.6414770",
    longitude: "-0.8039321",
    description: "West Wycombe Park is a Palladian country house set within landscaped grounds created by Sir Francis Dashwood in the 18th century. The house contains a magnificent collection of tapestries, furniture and paintings, while the grounds feature a lake, temples and classical follies inspired by Dashwood's Grand Tour of Italy. The estate also includes West Wycombe village and the iconic golden ball atop St Lawrence's Church on the hill above.",
    shortDescription: "Palladian mansion with 18th-century landscaped park, classical temples and the Dashwood family's Grand Tour collections.",
    websiteUrl: "https://www.nationaltrust.org.uk/visit/oxfordshire-buckinghamshire-berkshire/west-wycombe-park-village-and-hill",
    heroImageUrl: "https://upload.wikimedia.org/wikipedia/commons/c/cc/The_South_Front_of_West_Wycombe_Park.jpg",
    pricing: [
      { pricingType: "entry", pricingCategory: "standard", tier: "adult", nonMemberPrice: "12.00", memberPrice: null, label: "Adult (18+)" },
      { pricingType: "entry", pricingCategory: "standard", tier: "child", nonMemberPrice: "6.00", memberPrice: null, label: "Child (5-17)" },
      { pricingType: "entry", pricingCategory: "standard", tier: "family", nonMemberPrice: "30.00", memberPrice: null, label: "Family (2 adults + 3 children)" },
    ],
  },
  {
    name: "Peckover House",
    slug: slugify("Peckover House"),
    category: "house",
    region: "Cambridgeshire",
    latitude: "52.6650765",
    longitude: "0.1553992",
    description: "Peckover House is an elegant Georgian townhouse in the heart of Wisbech, home to the Peckover banking family for over 150 years. The house contains fine plasterwork, wood panelling and an outstanding collection of paintings. The real treasure lies behind the house — a two-acre Victorian garden featuring orangery, summer houses, croquet lawn, herbaceous borders and over 60 varieties of rose.",
    shortDescription: "Georgian townhouse in Wisbech with fine interiors and a hidden two-acre Victorian garden of roses and borders.",
    websiteUrl: "https://www.nationaltrust.org.uk/peckover-house-and-garden",
    heroImageUrl: "https://upload.wikimedia.org/wikipedia/commons/7/77/Peckover-house-wisbech.jpg",
    pricing: [],
  },
  {
    name: "Trengwainton Garden",
    slug: slugify("Trengwainton Garden"),
    category: "garden",
    region: "Cornwall",
    latitude: "50.1273120",
    longitude: "-5.5672685",
    description: "Trengwainton Garden is a lush subtropical paradise near Penzance, sheltered by ancient woodland and warmed by the Gulf Stream. The garden is renowned for its walled gardens featuring a series of small compartments originally built to grow exotic fruits and vegetables. Magnolias, camellias, tree ferns and rhododendrons thrive here, and many rare species were first grown in Britain at Trengwainton from seeds collected by plant hunters in the Himalayas and Burma.",
    shortDescription: "Subtropical garden near Penzance with rare plants, walled gardens and sweeping views across Mount's Bay.",
    websiteUrl: "https://www.nationaltrust.org.uk/visit/cornwall/trengwainton-garden",
    heroImageUrl: "https://upload.wikimedia.org/wikipedia/commons/e/e7/Pond%2C_Trengwainton.JPG",
    pricing: [
      { pricingType: "entry", pricingCategory: "garden-only", tier: "adult", nonMemberPrice: "14.00", memberPrice: null, label: "Adult (18+)" },
      { pricingType: "entry", pricingCategory: "garden-only", tier: "child", nonMemberPrice: "7.00", memberPrice: null, label: "Child (5-17)" },
      { pricingType: "entry", pricingCategory: "garden-only", tier: "family", nonMemberPrice: "35.00", memberPrice: null, label: "Family (2 adults + 3 children)" },
    ],
  },
  {
    name: "A La Ronde",
    slug: slugify("A La Ronde"),
    category: "house",
    region: "Devon",
    latitude: "50.6416839",
    longitude: "-3.4088488",
    description: "A La Ronde is a unique 16-sided house built in 1796 for two spinster cousins, Jane and Mary Parminter, inspired by the Byzantine basilica of San Vitale in Ravenna. The interior is filled with extraordinary decorative work including a shell gallery made from 25,000 shells, feather friezes and sand-and-seaweed pictures. The house offers panoramic views across the Exe estuary from its quirky diamond-shaped and hexagonal windows.",
    shortDescription: "Unique 16-sided Georgian house near Exmouth with a shell gallery and panoramic estuary views.",
    websiteUrl: "https://www.nationaltrust.org.uk/visit/devon/a-la-ronde",
    heroImageUrl: "https://upload.wikimedia.org/wikipedia/commons/c/c1/A_La_Ronde_%285523285615%29.jpg",
    pricing: [
      { pricingType: "entry", pricingCategory: "standard", tier: "adult", nonMemberPrice: "12.00", memberPrice: null, label: "Adult (18+)" },
      { pricingType: "entry", pricingCategory: "standard", tier: "child", nonMemberPrice: "6.00", memberPrice: null, label: "Child (5-17)" },
      { pricingType: "entry", pricingCategory: "standard", tier: "family", nonMemberPrice: "30.00", memberPrice: null, label: "Family (2 adults + 3 children)" },
    ],
  },
  {
    name: "Lydford Gorge",
    slug: slugify("Lydford Gorge"),
    category: "countryside",
    region: "Devon",
    latitude: "50.6414897",
    longitude: "-4.1098351",
    description: "Lydford Gorge is the deepest river gorge in the South West, carved out by the River Lyd over thousands of years on the edge of Dartmoor. The dramatic one-and-a-half-mile trail follows the river through ancient oak woodland past the thundering 30-metre White Lady Waterfall and the swirling whirlpools of the Devil's Cauldron. The gorge is a haven for wildlife including dippers, grey wagtails and over 40 species of lichen.",
    shortDescription: "Devon's deepest gorge with the White Lady Waterfall, Devil's Cauldron and ancient woodland trails.",
    websiteUrl: "https://www.nationaltrust.org.uk/visit/devon/lydford-gorge",
    heroImageUrl: "https://upload.wikimedia.org/wikipedia/commons/7/74/WhiteLadyLydfordGorge.jpg",
    pricing: [
      { pricingType: "entry", pricingCategory: "standard", tier: "adult", nonMemberPrice: "13.00", memberPrice: null, label: "Adult (18+)" },
      { pricingType: "entry", pricingCategory: "standard", tier: "child", nonMemberPrice: "6.50", memberPrice: null, label: "Child (5-17)" },
      { pricingType: "entry", pricingCategory: "standard", tier: "family", nonMemberPrice: "32.50", memberPrice: null, label: "Family (2 adults + 3 children)" },
    ],
  },
  {
    name: "Overbeck's",
    slug: slugify("Overbeck's"),
    category: "house",
    region: "Devon",
    latitude: "50.2229475",
    longitude: "-3.7839760",
    description: "Overbeck's is a striking Edwardian house perched above the Salcombe estuary with spectacular views across the South Devon coast. Named after its last owner, the eccentric inventor and scientist Otto Overbeck, the house contains his quirky collection of curiosities. The six-acre garden is one of the most remarkable in the country, where exotic plants from the Mediterranean, South Africa and South America thrive in the mild maritime climate.",
    shortDescription: "Edwardian house above Salcombe with an eccentric inventor's collection and exotic subtropical garden.",
    websiteUrl: "https://www.nationaltrust.org.uk/visit/devon/overbecks-garden",
    heroImageUrl: "https://upload.wikimedia.org/wikipedia/commons/7/7d/Overbeck%27s_Gate_Sign.jpg",
    pricing: [
      { pricingType: "entry", pricingCategory: "standard", tier: "adult", nonMemberPrice: "12.00", memberPrice: null, label: "Adult (18+)" },
      { pricingType: "entry", pricingCategory: "standard", tier: "child", nonMemberPrice: "6.00", memberPrice: null, label: "Child (5-17)" },
      { pricingType: "entry", pricingCategory: "standard", tier: "family", nonMemberPrice: "30.00", memberPrice: null, label: "Family (2 adults + 3 children)" },
    ],
  },
  {
    name: "Melford Hall",
    slug: slugify("Melford Hall"),
    category: "house",
    region: "Suffolk",
    latitude: "52.0825944",
    longitude: "0.7226342",
    description: "Melford Hall is a turreted Tudor mansion in the village of Long Melford, home to the Hyde Parker family since 1786. The house has a distinguished history — Elizabeth I was entertained here lavishly in 1578, and Beatrix Potter was a regular visitor who used the hall as inspiration for The Tale of Jemima Puddle-Duck. The interior features a Regency library, Victorian bedrooms and a collection of Chinese porcelain, while the grounds include a charming walled garden and parkland.",
    shortDescription: "Turreted Tudor mansion at Long Melford with Beatrix Potter connections and a fine walled garden.",
    websiteUrl: "https://www.nationaltrust.org.uk/visit/suffolk/melford-hall",
    heroImageUrl: "https://upload.wikimedia.org/wikipedia/commons/7/73/Melford_Hall.jpg",
    pricing: [
      { pricingType: "entry", pricingCategory: "standard", tier: "adult", nonMemberPrice: "14.00", memberPrice: null, label: "Adult (18+)" },
      { pricingType: "entry", pricingCategory: "standard", tier: "child", nonMemberPrice: "7.00", memberPrice: null, label: "Child (5-17)" },
      { pricingType: "entry", pricingCategory: "standard", tier: "family", nonMemberPrice: "35.00", memberPrice: null, label: "Family (2 adults + 3 children)" },
    ],
  },
  {
    name: "Orford Ness",
    slug: slugify("Orford Ness"),
    category: "coast",
    region: "Suffolk",
    latitude: "52.0872648",
    longitude: "1.5536753",
    description: "Orford Ness is Europe's largest vegetated shingle spit, a wild and hauntingly beautiful landscape stretching along the Suffolk coast. This remote peninsula has a remarkable secret history as a military test site where radar, atomic weapons triggers and other Cold War technologies were developed behind closed doors. Now returned to nature, the Ness is home to rare shingle plants, breeding birds and the eerie remains of the pagoda-shaped test buildings.",
    shortDescription: "Europe's largest shingle spit with a secret Cold War history and rare wildlife on the Suffolk coast.",
    websiteUrl: "https://www.nationaltrust.org.uk/orford-ness",
    heroImageUrl: "https://upload.wikimedia.org/wikipedia/commons/3/39/Looking_towards_Orford_Ness_from_Orford_castle_-_geograph.org.uk_-_1755769.jpg",
    pricing: [],
  },
  {
    name: "Hatfield Forest",
    slug: slugify("Hatfield Forest"),
    category: "countryside",
    region: "Essex",
    latitude: "51.8574054",
    longitude: "0.2295635",
    description: "Hatfield Forest is one of the finest surviving examples of a medieval royal hunting forest in England, remarkably intact after 1,000 years. The forest contains ancient coppiced woodland, wood pasture, a lake created in the 18th century and an ornamental Shell House. It is home to great crested newts, 15 species of bat, purple emperor butterflies and over 1,000 species of beetle. The wide green rides and open plains still reflect its original medieval structure.",
    shortDescription: "A thousand-year-old royal hunting forest with ancient woodland, a lake and an ornamental Shell House.",
    websiteUrl: "https://www.nationaltrust.org.uk/hatfield-forest",
    heroImageUrl: "https://upload.wikimedia.org/wikipedia/commons/4/42/Hatfield_Forest_1.png",
    pricing: [],
  },
  {
    name: "Chastleton House",
    slug: slugify("Chastleton House"),
    category: "house",
    region: "Oxfordshire",
    latitude: "51.9597462",
    longitude: "-1.6401271",
    description: "Chastleton House is a Jacobean country house built between 1607 and 1612 by a wealthy wool merchant, remarkable for remaining in the same family for nearly 400 years without major alteration. The house is filled with a mixture of rare and everyday objects accumulated over centuries, giving an authentic and unrestored atmosphere quite unlike grander stately homes. The garden features one of England's first croquet lawns — the rules of modern croquet were codified here in 1865 — and topiary dating from the 17th century.",
    shortDescription: "Atmospheric unrestored Jacobean house in the Cotswolds where the rules of modern croquet were written.",
    websiteUrl: "https://www.nationaltrust.org.uk/chastleton-house",
    heroImageUrl: "https://upload.wikimedia.org/wikipedia/commons/c/cf/Chastleton_House_-_front.jpg",
    pricing: [
      { pricingType: "entry", pricingCategory: "standard", tier: "adult", nonMemberPrice: "15.00", memberPrice: null, label: "Adult (18+)" },
      { pricingType: "entry", pricingCategory: "standard", tier: "child", nonMemberPrice: "7.50", memberPrice: null, label: "Child (5-17)" },
      { pricingType: "entry", pricingCategory: "standard", tier: "family", nonMemberPrice: "37.50", memberPrice: null, label: "Family (2 adults + 3 children)" },
    ],
  },
  {
    name: "Nuffield Place",
    slug: slugify("Nuffield Place"),
    category: "house",
    region: "Oxfordshire",
    latitude: "51.5849575",
    longitude: "-1.0216579",
    description: "Nuffield Place was the modest home of William Morris, Viscount Nuffield, the founder of Morris Motors and one of the greatest philanthropists of the 20th century. Despite his enormous wealth, Morris chose to live simply in this comfortable 1930s house filled with his personal belongings, from his collection of clocks to his Wolseley car in the garage. The house and gardens offer a fascinating glimpse into the private life of the man who shaped modern British industry.",
    shortDescription: "Modest 1930s home of Morris Motors founder Viscount Nuffield, filled with personal treasures and period gardens.",
    websiteUrl: "https://www.nationaltrust.org.uk/visit/oxfordshire-buckinghamshire-berkshire/nuffield-place",
    heroImageUrl: "https://upload.wikimedia.org/wikipedia/commons/0/0d/Nuffield_Place-4311428181.jpg",
    pricing: [
      { pricingType: "entry", pricingCategory: "standard", tier: "adult", nonMemberPrice: "14.00", memberPrice: null, label: "Adult (18+)" },
      { pricingType: "entry", pricingCategory: "standard", tier: "child", nonMemberPrice: "7.00", memberPrice: null, label: "Child (5-17)" },
      { pricingType: "entry", pricingCategory: "standard", tier: "family", nonMemberPrice: "35.00", memberPrice: null, label: "Family (2 adults + 3 children)" },
    ],
  },
  {
    name: "Runnymede",
    slug: slugify("Runnymede"),
    category: "historic-site",
    region: "Surrey",
    latitude: "51.4388382",
    longitude: "-0.5544523",
    description: "Runnymede is the historic meadow on the banks of the River Thames where King John sealed the Magna Carta in 1215, establishing the principles of justice and liberty that have influenced democracies around the world. The riverside landscape includes the Magna Carta Memorial built by the American Bar Association, the John F. Kennedy Memorial set within an acre of English ground given to the United States, and the Commonwealth Air Forces Memorial commemorating over 20,000 airmen who lost their lives in World War II.",
    shortDescription: "Historic Thames-side meadow where the Magna Carta was sealed in 1215, with three poignant memorials.",
    websiteUrl: "https://www.nationaltrust.org.uk/runnymede",
    heroImageUrl: "https://upload.wikimedia.org/wikipedia/commons/5/55/RunnymedeMagnacartaisle.jpg",
    pricing: [],
  },
  {
    name: "Leith Hill",
    slug: slugify("Leith Hill"),
    category: "countryside",
    region: "Surrey",
    latitude: "51.1768174",
    longitude: "-0.3714155",
    description: "Leith Hill is the highest point in south-east England at 294 metres, crowned by an 18th-century Gothic tower built by Richard Hull of Leith Hill Place. Climbing the tower takes visitors above 1,000 feet with far-reaching views across the Weald to the South Downs and, on clear days, to the English Channel. The surrounding estate includes ancient woodland, rhododendron walks, and Leith Hill Place, a house with connections to composer Ralph Vaughan Williams who grew up here.",
    shortDescription: "Highest point in south-east England with a Gothic tower, sweeping views and woodland walks.",
    websiteUrl: "https://www.nationaltrust.org.uk/leith-hill",
    heroImageUrl: "https://upload.wikimedia.org/wikipedia/en/2/2e/Leith_hill_07.jpg",
    pricing: [
      { pricingType: "entry", pricingCategory: "standard", tier: "adult", nonMemberPrice: "3.50", memberPrice: null, label: "Adult (18+) - Tower" },
      { pricingType: "entry", pricingCategory: "standard", tier: "child", nonMemberPrice: "1.50", memberPrice: null, label: "Child (5-17) - Tower" },
    ],
  },
  {
    name: "Hindhead Common",
    slug: slugify("Hindhead Common"),
    category: "countryside",
    region: "Surrey",
    latitude: "51.1136180",
    longitude: "-0.7320730",
    description: "Hindhead Common and the Devil's Punch Bowl form one of the largest areas of open heath in Surrey, a dramatic landscape of purple heather, golden gorse and ancient Scots pine. The Devil's Punch Bowl is a vast natural amphitheatre carved by springs during the last Ice Age, offering spectacular walking routes around its rim and down to the valley floor. Since the opening of the Hindhead Tunnel, the old A3 road has been removed and the common is now reunited for the first time in over a century.",
    shortDescription: "Dramatic heathland and the Devil's Punch Bowl, a vast natural amphitheatre in the Surrey Hills.",
    websiteUrl: "https://www.nationaltrust.org.uk/hindhead-commons-and-the-devils-punch-bowl",
    heroImageUrl: "https://upload.wikimedia.org/wikipedia/commons/6/64/Celtic_cross_on_Gibbet_Hill.JPG",
    pricing: [],
  },
  {
    name: "Shaw's Corner",
    slug: slugify("Shaw's Corner"),
    category: "house",
    region: "Hertfordshire",
    latitude: "51.8358465",
    longitude: "-0.2686256",
    description: "Shaw's Corner is the former home of George Bernard Shaw, the Nobel Prize-winning playwright, who lived here from 1906 until his death in 1950. The Edwardian Arts and Crafts house remains much as Shaw left it, with his desk, typewriter and personal belongings offering an intimate portrait of one of the 20th century's greatest literary figures. At the bottom of the garden stands his famous revolving writing hut, designed so he could always work facing the sun.",
    shortDescription: "Edwardian home of Nobel laureate George Bernard Shaw, with his famous revolving garden writing hut.",
    websiteUrl: "https://www.nationaltrust.org.uk/visit/essex-bedfordshire-hertfordshire/shaws-corner",
    heroImageUrl: "https://upload.wikimedia.org/wikipedia/commons/c/c5/Shaw%27s_Corner1.jpg",
    pricing: [
      { pricingType: "entry", pricingCategory: "standard", tier: "adult", nonMemberPrice: "11.00", memberPrice: null, label: "Adult (18+)" },
      { pricingType: "entry", pricingCategory: "standard", tier: "child", nonMemberPrice: "5.50", memberPrice: null, label: "Child (5-17)" },
      { pricingType: "entry", pricingCategory: "standard", tier: "family", nonMemberPrice: "27.50", memberPrice: null, label: "Family (2 adults + 3 children)" },
    ],
  },
  {
    name: "Sandham Memorial Chapel",
    slug: slugify("Sandham Memorial Chapel"),
    category: "historic-site",
    region: "Hampshire",
    latitude: "51.3446451",
    longitude: "-1.3362120",
    description: "Sandham Memorial Chapel houses one of the greatest sets of paintings created in Britain in the 20th century — a cycle of monumental murals by Stanley Spencer inspired by his experiences as a soldier in World War I. The paintings, which took Spencer six years to complete, cover every wall of the purpose-built chapel and culminate in a vast Resurrection scene on the altar wall. Built in the 1920s to commemorate Lieutenant Henry Willoughby Sandham, the chapel is often compared to Giotto's Arena Chapel in Padua.",
    shortDescription: "Purpose-built chapel housing Stanley Spencer's monumental World War I murals, a masterpiece of 20th-century art.",
    websiteUrl: "https://www.nationaltrust.org.uk/visit/hampshire/sandham-memorial-chapel",
    heroImageUrl: "https://upload.wikimedia.org/wikipedia/commons/9/96/Sandham_Memorial_Chapel%2C_Burghclere_-_geograph.org.uk_-_27053.jpg",
    pricing: [
      { pricingType: "entry", pricingCategory: "standard", tier: "adult", nonMemberPrice: "12.00", memberPrice: null, label: "Adult (18+)" },
      { pricingType: "entry", pricingCategory: "standard", tier: "child", nonMemberPrice: "6.00", memberPrice: null, label: "Child (5-17)" },
      { pricingType: "entry", pricingCategory: "standard", tier: "family", nonMemberPrice: "30.00", memberPrice: null, label: "Family (2 adults + 3 children)" },
    ],
  },
  {
    name: "Alfriston Clergy House",
    slug: slugify("Alfriston Clergy House"),
    category: "historic-site",
    region: "East Sussex",
    latitude: "50.8061650",
    longitude: "0.1577850",
    description: "Alfriston Clergy House is a 14th-century thatched Wealden hall house that in 1896 became the very first building acquired by the National Trust, purchased for just £10. This beautifully preserved medieval timber-framed house features a rare chalk and sour milk floor in the hall, and a charming cottage garden filled with traditional plants. Set beside St Andrew's Church on the village green known as the Tye, it provides a delightful picture of rural Sussex life.",
    shortDescription: "The first building acquired by the National Trust in 1896 — a charming 14th-century thatched hall house.",
    websiteUrl: "https://www.nationaltrust.org.uk/visit/sussex/alfriston-clergy-house",
    heroImageUrl: "https://upload.wikimedia.org/wikipedia/commons/5/53/The_Clergy_House%2C_Alfriston_-_geograph.org.uk_-_1260729.jpg",
    pricing: [
      { pricingType: "entry", pricingCategory: "standard", tier: "adult", nonMemberPrice: "10.00", memberPrice: null, label: "Adult (18+)" },
      { pricingType: "entry", pricingCategory: "standard", tier: "child", nonMemberPrice: "5.00", memberPrice: null, label: "Child (5-17)" },
      { pricingType: "entry", pricingCategory: "standard", tier: "family", nonMemberPrice: "25.00", memberPrice: null, label: "Family (2 adults + 3 children)" },
    ],
  },
  {
    name: "Lamb House",
    slug: slugify("Lamb House"),
    category: "house",
    region: "East Sussex",
    latitude: "50.9498807",
    longitude: "0.7327329",
    description: "Lamb House is a handsome Georgian house on a cobbled street in the hilltop town of Rye, famous as the home of the novelist Henry James from 1898 to 1916. James wrote some of his greatest works here, including The Wings of the Dove and The Golden Bowl. The house was later home to E.F. Benson, author of the Mapp and Lucia novels, who used the house as the model for Miss Mapp's home. The walled garden provides a peaceful retreat with herbaceous borders and fine views.",
    shortDescription: "Georgian house in Rye, home to novelists Henry James and E.F. Benson, with a walled garden.",
    websiteUrl: "https://www.nationaltrust.org.uk/visit/sussex/lamb-house",
    heroImageUrl: "https://upload.wikimedia.org/wikipedia/commons/9/9d/LAMB_HOUSE%2C_RYE%2C_ENGLAND.jpg",
    pricing: [
      { pricingType: "entry", pricingCategory: "standard", tier: "adult", nonMemberPrice: "10.00", memberPrice: null, label: "Adult (18+)" },
      { pricingType: "entry", pricingCategory: "standard", tier: "child", nonMemberPrice: "5.00", memberPrice: null, label: "Child (5-17)" },
      { pricingType: "entry", pricingCategory: "standard", tier: "family", nonMemberPrice: "25.00", memberPrice: null, label: "Family (2 adults + 3 children)" },
    ],
  },
  {
    name: "Woolbeding Gardens",
    slug: slugify("Woolbeding Gardens"),
    category: "garden",
    region: "West Sussex",
    latitude: "50.9973630",
    longitude: "-0.7578880",
    description: "Woolbeding Gardens are a series of enchanting garden rooms surrounding an Elizabethan manor house in the South Downs. The gardens blend formal design with wild planting to dramatic effect, featuring a modern parterre, a riverside walk along the River Rother, and the spectacular Tulip Folly designed by Julian and Isabel Bannerman. Pre-booking is required as the gardens open only on selected days, and visitors arrive via a shuttle bus to preserve the tranquil atmosphere.",
    shortDescription: "Enchanting garden rooms in the South Downs with the spectacular Tulip Folly and riverside walks.",
    websiteUrl: "https://www.nationaltrust.org.uk/visit/sussex/woolbeding-gardens",
    heroImageUrl: "https://upload.wikimedia.org/wikipedia/commons/0/09/Woolbeding_church_tower_-_geograph.org.uk_-_1186502.jpg",
    pricing: [
      { pricingType: "entry", pricingCategory: "garden-only", tier: "adult", nonMemberPrice: "14.00", memberPrice: null, label: "Adult (18+)" },
      { pricingType: "entry", pricingCategory: "garden-only", tier: "child", nonMemberPrice: "7.00", memberPrice: null, label: "Child (5-17)" },
    ],
  },
  {
    name: "Morden Hall Park",
    slug: slugify("Morden Hall Park"),
    category: "countryside",
    region: "London",
    latitude: "51.4027293",
    longitude: "-0.1859361",
    description: "Morden Hall Park is a green oasis in the heart of suburban south London, 125 acres of parkland, wetland and waterways along the River Wandle. Once a deer park and later the estate of the Hatfeild snuff milling family, the park features a beautiful rose garden with over 2,000 roses, ancient hay meadows, a network of waterways and wetlands that support kingfishers and herons, and historic buildings including a former snuff mill.",
    shortDescription: "A 125-acre green oasis in south London with riverside walks, wetlands and a rose garden of 2,000 blooms.",
    websiteUrl: "https://www.nationaltrust.org.uk/morden-hall-park",
    heroImageUrl: "https://upload.wikimedia.org/wikipedia/commons/1/14/MordenHall.jpg",
    pricing: [],
  },
  {
    name: "Carlyle's House",
    slug: slugify("Carlyle's House"),
    category: "house",
    region: "London",
    latitude: "51.4840807",
    longitude: "-0.1698022",
    description: "Carlyle's House is an elegant Queen Anne terraced house in Chelsea where the Scottish historian and essayist Thomas Carlyle and his wife Jane lived from 1834 until their deaths. The house is preserved much as the Carlyles knew it, with their books, furniture and personal possessions offering an intimate picture of Victorian literary life. Famous visitors included Charles Dickens, John Ruskin, Alfred Tennyson and Charles Darwin. The small walled garden provides a quiet refuge from the bustle of Chelsea.",
    shortDescription: "Victorian literary home of Thomas Carlyle in Chelsea, visited by Dickens, Tennyson and Darwin.",
    websiteUrl: "https://www.nationaltrust.org.uk/visit/london/carlyles-house",
    heroImageUrl: "https://upload.wikimedia.org/wikipedia/commons/e/e5/Thomas_Carlyle_House_-_24_Cheyne_Row_Chelsea_London_SW3_5HL.jpg",
    pricing: [
      { pricingType: "entry", pricingCategory: "standard", tier: "adult", nonMemberPrice: "12.00", memberPrice: null, label: "Adult (18+)" },
      { pricingType: "entry", pricingCategory: "standard", tier: "child", nonMemberPrice: "6.00", memberPrice: null, label: "Child (5-17)" },
      { pricingType: "entry", pricingCategory: "standard", tier: "family", nonMemberPrice: "30.00", memberPrice: null, label: "Family (2 adults + 3 children)" },
    ],
  },
  {
    name: "Sutton House",
    slug: slugify("Sutton House"),
    category: "house",
    region: "London",
    latitude: "51.5484892",
    longitude: "-0.0503803",
    description: "Sutton House is a rare Tudor red-brick house in Hackney, the oldest domestic building in East London, built in 1535 for Sir Ralph Sadleir, a courtier of Henry VIII. Behind its Georgian facade lie original Tudor rooms including linenfold panelling, carved fireplaces and a painted Jacobean staircase. The Breaker's Yard, added later, offers a contrast with its contemporary art exhibitions and community spaces. The house has been everything from a girls' school to a squat during its varied history.",
    shortDescription: "East London's oldest domestic building — a Tudor red-brick house in Hackney with 500 years of stories.",
    websiteUrl: "https://www.nationaltrust.org.uk/sutton-house-and-breakers-yard",
    heroImageUrl: "https://upload.wikimedia.org/wikipedia/commons/8/8b/Sutton_House_in_Hackney_Exterior.jpg",
    pricing: [],
  },
  {
    name: "Penshaw Monument",
    slug: slugify("Penshaw Monument"),
    category: "historic-site",
    region: "Tyne and Wear",
    latitude: "54.8830401",
    longitude: "-1.4808529",
    description: "Penshaw Monument is a striking half-sized replica of the Temple of Hephaestus in Athens, perched dramatically on top of Penshaw Hill in Sunderland. Built in 1844 to commemorate John George Lambton, the first Earl of Durham and the first Governor of Canada, the monument is a much-loved local landmark visible for miles across the surrounding countryside. Guided tours allow visitors to climb the internal staircase for panoramic views across Wearside.",
    shortDescription: "Dramatic Greek-style temple on a hilltop near Sunderland, a beloved North East landmark since 1844.",
    websiteUrl: "https://www.nationaltrust.org.uk/penshaw-monument",
    heroImageUrl: "https://upload.wikimedia.org/wikipedia/commons/1/17/Steps_to_the_Penshaw_Monument_%28geograph_5719013%29.jpg",
    pricing: [],
  },
  {
    name: "Hardcastle Crags",
    slug: slugify("Hardcastle Crags"),
    category: "countryside",
    region: "West Yorkshire",
    latitude: "53.7691193",
    longitude: "-2.0430356",
    description: "Hardcastle Crags is a deeply wooded Pennine valley near Hebden Bridge, a haven of tumbling streams, mossy boulders and ancient oak woodland. At the heart of the valley stands Gibson Mill, a former cotton mill now powered entirely by renewable energy and serving as an interactive exhibition about sustainable living. The crags themselves are outcrops of millstone grit scattered through the woodland, and the valley supports a rich variety of wildlife including dippers, kingfishers and rare moths.",
    shortDescription: "Wooded Pennine valley near Hebden Bridge with Gibson Mill, tumbling streams and millstone grit crags.",
    websiteUrl: "https://www.nationaltrust.org.uk/hardcastle-crags",
    heroImageUrl: "https://upload.wikimedia.org/wikipedia/commons/8/82/Gibson_Mill.jpg",
    pricing: [],
  },
  {
    name: "Farne Islands",
    slug: slugify("Farne Islands"),
    category: "coast",
    region: "Northumberland",
    latitude: "55.6311501",
    longitude: "-1.6302182",
    description: "The Farne Islands are a group of rocky islands off the Northumberland coast, home to one of Europe's most spectacular seabird colonies. Between May and July, Inner Farne is alive with puffins, Arctic terns, guillemots, razorbills and shags nesting at extraordinarily close range. The islands have a long history as a place of Christian pilgrimage — St Cuthbert lived here as a hermit in the 7th century. Grey seals breed on the islands in autumn, with over 2,000 pups born each year.",
    shortDescription: "Spectacular Northumberland seabird colony with thousands of puffins, Arctic terns and breeding grey seals.",
    websiteUrl: "https://www.nationaltrust.org.uk/farne-islands",
    heroImageUrl: "https://upload.wikimedia.org/wikipedia/commons/5/59/Inner_Farne_Wide_View.jpg",
    pricing: [
      { pricingType: "entry", pricingCategory: "standard", tier: "adult", nonMemberPrice: "13.00", memberPrice: null, label: "Adult (18+) - Off peak" },
      { pricingType: "entry", pricingCategory: "standard", tier: "child", nonMemberPrice: "6.50", memberPrice: null, label: "Child (5-17) - Off peak" },
      { pricingType: "entry", pricingCategory: "standard", tier: "family", nonMemberPrice: "32.50", memberPrice: null, label: "Family (2 adults + 3 children) - Off peak" },
    ],
  },
  {
    name: "Carding Mill Valley",
    slug: slugify("Carding Mill Valley"),
    category: "countryside",
    region: "Shropshire",
    latitude: "52.5458333",
    longitude: "-2.8225000",
    description: "Carding Mill Valley is a beautiful valley carved into the Long Mynd, a dramatic moorland plateau in the Shropshire Hills. Named after the textile mills that once operated here, the valley offers walks ranging from gentle strolls along the stream to challenging hikes up to the windswept summit with views across to Wales. The stream that runs through the valley is popular with families for paddling and dam-building, while the surrounding moorland supports skylarks, red grouse and dippers.",
    shortDescription: "Scenic Shropshire valley in the Long Mynd with stream walks, moorland hikes and views to Wales.",
    websiteUrl: "https://www.nationaltrust.org.uk/carding-mill-valley-and-the-long-mynd",
    heroImageUrl: "https://upload.wikimedia.org/wikipedia/commons/2/22/Church_Stretton_Ragleth_2010_1.jpg",
    pricing: [],
  },
  {
    name: "Benthall Hall",
    slug: slugify("Benthall Hall"),
    category: "house",
    region: "Shropshire",
    latitude: "52.6202253",
    longitude: "-2.5064368",
    description: "Benthall Hall is a fine 16th-century stone house near Ironbridge, home to the Benthall family and their descendants for over 500 years. The house features elaborate plasterwork ceilings, carved oak staircases and an intriguing collection of geology specimens reflecting the area's rich industrial heritage. The garden is a delight in spring with masses of crocuses, and the surrounding estate includes woodland walks with views over the Severn Gorge.",
    shortDescription: "16th-century stone house near Ironbridge with fine plasterwork, spring crocuses and Severn Gorge views.",
    websiteUrl: "https://www.nationaltrust.org.uk/benthall-hall",
    heroImageUrl: "https://upload.wikimedia.org/wikipedia/commons/d/d6/Benthall_Hall_A.jpg",
    pricing: [
      { pricingType: "entry", pricingCategory: "standard", tier: "adult", nonMemberPrice: "11.00", memberPrice: null, label: "Adult (18+)" },
      { pricingType: "entry", pricingCategory: "standard", tier: "child", nonMemberPrice: "5.50", memberPrice: null, label: "Child (5-17)" },
      { pricingType: "entry", pricingCategory: "standard", tier: "family", nonMemberPrice: "27.50", memberPrice: null, label: "Family (2 adults + 3 children)" },
    ],
  },
  {
    name: "Kinver Edge",
    slug: slugify("Kinver Edge"),
    category: "countryside",
    region: "Staffordshire",
    latitude: "52.4498633",
    longitude: "-2.2420987",
    description: "Kinver Edge is a dramatic sandstone ridge on the Staffordshire-Worcestershire border, famous for its extraordinary rock houses carved into the soft red sandstone. People lived in these rock-cut dwellings from the 17th century until the 1960s, and the National Trust has restored several to show different periods of their history. The heathland above offers panoramic views across the Midlands, while the Holy Austin Rock houses are the last troglodyte dwellings in England.",
    shortDescription: "Sandstone ridge with the last troglodyte rock houses in England and panoramic Midlands views.",
    websiteUrl: "https://www.nationaltrust.org.uk/kinver-edge-and-the-rock-houses",
    heroImageUrl: "https://upload.wikimedia.org/wikipedia/commons/7/79/View_of_Kinver_from_Rock_Houses.JPG",
    pricing: [
      { pricingType: "entry", pricingCategory: "standard", tier: "adult", nonMemberPrice: "9.00", memberPrice: null, label: "Adult (18+) - Rock Houses" },
      { pricingType: "entry", pricingCategory: "standard", tier: "child", nonMemberPrice: "4.50", memberPrice: null, label: "Child (5-17) - Rock Houses" },
      { pricingType: "entry", pricingCategory: "standard", tier: "family", nonMemberPrice: "22.50", memberPrice: null, label: "Family (2 adults + 3 children) - Rock Houses" },
    ],
  },
  {
    name: "Clevedon Court",
    slug: slugify("Clevedon Court"),
    category: "house",
    region: "Somerset",
    latitude: "51.4402250",
    longitude: "-2.8321420",
    description: "Clevedon Court is a remarkably well-preserved medieval manor house with origins dating to the early 14th century, one of the few surviving houses of its period. The house incorporates elements from every century since its construction, including a 13th-century tower, 14th-century great hall and an elegant 18th-century hanging staircase. The terraced garden, perched on a hillside with views across the Bristol Channel to Wales, features rare and tender plants sheltered by ancient yew trees.",
    shortDescription: "One of England's finest medieval manor houses, with 700 years of architecture and terraced gardens overlooking the Bristol Channel.",
    websiteUrl: "https://www.nationaltrust.org.uk/clevedon-court",
    heroImageUrl: "https://upload.wikimedia.org/wikipedia/commons/9/92/Clevedon_2_%28front%2C_2011%29.jpg",
    pricing: [
      { pricingType: "entry", pricingCategory: "house-and-garden", tier: "adult", nonMemberPrice: "13.00", memberPrice: null, label: "Adult (18+)" },
      { pricingType: "entry", pricingCategory: "house-and-garden", tier: "child", nonMemberPrice: "6.50", memberPrice: null, label: "Child (5-17)" },
      { pricingType: "entry", pricingCategory: "house-and-garden", tier: "family", nonMemberPrice: "32.50", memberPrice: null, label: "Family (2 adults + 3 children)" },
      { pricingType: "entry", pricingCategory: "garden-only", tier: "adult", nonMemberPrice: "6.50", memberPrice: null, label: "Adult (18+)" },
      { pricingType: "entry", pricingCategory: "garden-only", tier: "child", nonMemberPrice: "3.25", memberPrice: null, label: "Child (5-17)" },
      { pricingType: "entry", pricingCategory: "garden-only", tier: "family", nonMemberPrice: "16.25", memberPrice: null, label: "Family (2 adults + 3 children)" },
    ],
  },
  {
    name: "Tintinhull Garden",
    slug: slugify("Tintinhull Garden"),
    category: "garden",
    region: "Somerset",
    latitude: "50.9750000",
    longitude: "-2.7096960",
    description: "Tintinhull Garden is an exquisite small garden created around a 17th-century farmhouse in Somerset, widely considered one of the finest examples of a 20th-century English garden. The garden is designed as a series of interconnected outdoor rooms, each with its own colour theme and character, linked by paths and vistas. Planted by Phyllis Reiss between the 1930s and 1960s, and later maintained by the celebrated garden writer Penelope Hobhouse, the garden demonstrates the art of garden design on an intimate scale.",
    shortDescription: "Exquisite small garden of interconnected rooms around a 17th-century Somerset farmhouse, a masterclass in planting design.",
    websiteUrl: "https://www.nationaltrust.org.uk/visit/somerset/tintinhull-garden",
    heroImageUrl: "https://upload.wikimedia.org/wikipedia/commons/7/75/Tintinhull_house.jpg",
    pricing: [
      { pricingType: "entry", pricingCategory: "garden-only", tier: "adult", nonMemberPrice: "9.00", memberPrice: null, label: "Adult (18+)" },
      { pricingType: "entry", pricingCategory: "garden-only", tier: "child", nonMemberPrice: "4.50", memberPrice: null, label: "Child (5-17)" },
      { pricingType: "entry", pricingCategory: "garden-only", tier: "family", nonMemberPrice: "22.50", memberPrice: null, label: "Family (2 adults + 3 children)" },
    ],
  },
];

async function addLocations() {
  const client = postgres(process.env.DATABASE_URL!);
  const db = drizzle(client);

  for (const loc of newLocations) {
    // Check if already exists
    const existing = await db
      .select({ id: locations.id })
      .from(locations)
      .where(eq(locations.slug, loc.slug))
      .limit(1);

    if (existing.length > 0) {
      console.log(`⏭️  Skipping "${loc.name}" (already exists)`);
      continue;
    }

    // Insert location
    const [inserted] = await db
      .insert(locations)
      .values({
        slug: loc.slug,
        name: loc.name,
        description: loc.description,
        shortDescription: loc.shortDescription,
        latitude: loc.latitude,
        longitude: loc.longitude,
        region: loc.region,
        category: loc.category,
        websiteUrl: loc.websiteUrl,
        heroImageUrl: loc.heroImageUrl,
        isPublished: true,
      })
      .returning({ id: locations.id });

    console.log(`✅ Added "${loc.name}" (id: ${inserted.id})`);

    // Insert pricing
    if (loc.pricing.length > 0) {
      await db.insert(locationPricing).values(
        loc.pricing.map((p) => ({
          locationId: inserted.id,
          pricingType: p.pricingType,
          pricingCategory: p.pricingCategory,
          tier: p.tier,
          nonMemberPrice: p.nonMemberPrice,
          memberPrice: p.memberPrice,
          label: p.label,
        }))
      );
      console.log(`   💰 Added ${loc.pricing.length} pricing entries`);
    }
  }

  console.log("\nDone!");
  await client.end();
}

addLocations().catch(console.error);
